"""restock_and_subscriptions

Revision ID: 22c45be7a060
Revises: 0013
Create Date: 2026-09-15 06:39:25.968049

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22c45be7a060'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('event_id', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_payment_events_provider_event')
    )
    op.create_table('subscription_plans',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('description_ar', sa.String(length=2000), nullable=True),
    sa.Column('description_en', sa.String(length=2000), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('annual_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_subscription_plans_code_version')
    )
    op.create_index(op.f('ix_subscription_plans_code'), 'subscription_plans', ['code'], unique=False)
    op.create_table('org_roles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'key', name='uq_org_roles_org_key')
    )
    op.create_index(op.f('ix_org_roles_organization_id'), 'org_roles', ['organization_id'], unique=False)
    op.create_table('organization_addons',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_addons_code'), 'organization_addons', ['code'], unique=False)
    op.create_index(op.f('ix_organization_addons_organization_id'), 'organization_addons', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_addons_status'), 'organization_addons', ['status'], unique=False)
    op.create_table('organization_subscriptions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_plan_id', sa.UUID(), nullable=True),
    sa.Column('proration_credit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ),
    sa.ForeignKeyConstraint(['pending_plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_subscriptions_organization_id'), 'organization_subscriptions', ['organization_id'], unique=True)
    op.create_index(op.f('ix_organization_subscriptions_status'), 'organization_subscriptions', ['status'], unique=False)
    op.create_table('usage_counters',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=60), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('warned_80', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'period_start', 'metric', name='uq_usage_counters_period')
    )
    op.create_index(op.f('ix_usage_counters_organization_id'), 'usage_counters', ['organization_id'], unique=False)
    op.create_table('usage_ledger',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_usage_ledger_metric'), 'usage_ledger', ['metric'], unique=False)
    op.create_index(op.f('ix_usage_ledger_organization_id'), 'usage_ledger', ['organization_id'], unique=False)
    op.create_table('wallets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('held_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_organization_id'), 'wallets', ['organization_id'], unique=True)
    op.create_table('subscription_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['organization_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_events_event_type'), 'subscription_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_subscription_events_organization_id'), 'subscription_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_subscription_events_subscription_id'), 'subscription_events', ['subscription_id'], unique=False)
    op.create_table('subscription_invoices',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['organization_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('subscription_id', 'period_start', name='uq_subscription_invoices_period')
    )
    op.create_index(op.f('ix_subscription_invoices_organization_id'), 'subscription_invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_subscription_invoices_provider_ref'), 'subscription_invoices', ['provider_ref'], unique=True)
    op.create_index(op.f('ix_subscription_invoices_status'), 'subscription_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_invoices_subscription_id'), 'subscription_invoices', ['subscription_id'], unique=False)
    op.create_table('team_invites',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['org_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_team_invites_email'), 'team_invites', ['email'], unique=False)
    op.create_index(op.f('ix_team_invites_organization_id'), 'team_invites', ['organization_id'], unique=False)
    op.create_table('wallet_entries',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('held_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_wallet_entries_entry_type'), 'wallet_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_wallet_entries_reference_id'), 'wallet_entries', ['reference_id'], unique=False)
    op.create_index(op.f('ix_wallet_entries_reference_type'), 'wallet_entries', ['reference_type'], unique=False)
    op.create_index(op.f('ix_wallet_entries_wallet_id'), 'wallet_entries', ['wallet_id'], unique=False)
    op.create_table('wallet_topups',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('redirect_url', sa.String(length=500), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_topups_provider_ref'), 'wallet_topups', ['provider_ref'], unique=True)
    op.create_index(op.f('ix_wallet_topups_status'), 'wallet_topups', ['status'], unique=False)
    op.create_index(op.f('ix_wallet_topups_wallet_id'), 'wallet_topups', ['wallet_id'], unique=False)
    op.create_table('withdrawal_requests',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_requests_status'), 'withdrawal_requests', ['status'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_wallet_id'), 'withdrawal_requests', ['wallet_id'], unique=False)
    op.create_table('promotions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('redemption_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_listing_id'), 'promotions', ['listing_id'], unique=False)
    op.create_index('ix_promotions_org_active', 'promotions', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_promotions_organization_id'), 'promotions', ['organization_id'], unique=False)
    op.create_table('restock_recommendations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('evidence_strength', sa.String(length=20), nullable=False),
    sa.Column('demand_window_days', sa.Integer(), nullable=True),
    sa.Column('incoming_qty', sa.Integer(), nullable=False),
    sa.Column('suggested_qty', sa.Integer(), nullable=False),
    sa.Column('suggested_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('days_of_cover', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('daily_velocity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('on_hand_qty', sa.Integer(), nullable=False),
    sa.Column('nearest_expiry_date', sa.Date(), nullable=True),
    sa.Column('expiry_zone', sa.String(length=20), nullable=False),
    sa.Column('market_median_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('matched_listing_id', sa.UUID(), nullable=True),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason_ar', sa.Text(), nullable=False),
    sa.Column('reason_en', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['pharmacy_branches.id'], ),
    sa.ForeignKeyConstraint(['matched_listing_id'], ['marketplace_listings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'product_id', 'kind', name='uq_restock_branch_product_kind')
    )
    op.create_index(op.f('ix_restock_recommendations_action'), 'restock_recommendations', ['action'], unique=False)
    op.create_index(op.f('ix_restock_recommendations_branch_id'), 'restock_recommendations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_restock_recommendations_kind'), 'restock_recommendations', ['kind'], unique=False)
    op.create_index(op.f('ix_restock_recommendations_organization_id'), 'restock_recommendations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_restock_recommendations_product_id'), 'restock_recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_restock_recommendations_status'), 'restock_recommendations', ['status'], unique=False)
    op.create_table('promotion_redemptions',
    sa.Column('promotion_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_redemptions_organization_id'), 'promotion_redemptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_promotion_redemptions_promotion_id'), 'promotion_redemptions', ['promotion_id'], unique=False)
    op.create_index('ix_promotion_redemptions_ref', 'promotion_redemptions', ['reference_type', 'reference_id'], unique=False)
    op.create_table('platform_revenue',
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['pharmacy_organizations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_revenue_collected_at'), 'platform_revenue', ['collected_at'], unique=False)
    op.create_index(op.f('ix_platform_revenue_kind'), 'platform_revenue', ['kind'], unique=False)
    op.create_index(op.f('ix_platform_revenue_organization_id'), 'platform_revenue', ['organization_id'], unique=False)
    op.create_index(op.f('ix_platform_revenue_transaction_id'), 'platform_revenue', ['transaction_id'], unique=False)
    op.drop_index('ix_audit_logs_org_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.drop_index('ix_import_jobs_queue', table_name='import_jobs')
    op.drop_index('ix_batches_branch_id', table_name='inventory_batches')
    op.drop_index('ix_batches_expiry_date', table_name='inventory_batches')
    op.drop_index('ix_batches_org_id', table_name='inventory_batches')
    op.drop_index('ix_batches_product_id', table_name='inventory_batches')
    op.drop_index('ix_batches_status', table_name='inventory_batches')
    op.create_index(op.f('ix_inventory_batches_branch_id'), 'inventory_batches', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_batches_expiry_date'), 'inventory_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_inventory_batches_organization_id'), 'inventory_batches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_batches_product_id'), 'inventory_batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_batches_status'), 'inventory_batches', ['status'], unique=False)
    op.drop_index('ix_movements_batch_id', table_name='inventory_movements')
    op.drop_index('ix_movements_org_id', table_name='inventory_movements')
    op.create_index(op.f('ix_inventory_movements_batch_id'), 'inventory_movements', ['batch_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_organization_id'), 'inventory_movements', ['organization_id'], unique=False)
    op.drop_constraint('invoices_transaction_id_key', 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_transaction_id'), 'invoices', ['transaction_id'], unique=True)
    op.drop_index('ix_offers_buyer_org_id', table_name='listing_offers')
    op.drop_index('ix_offers_listing_id', table_name='listing_offers')
    op.drop_index('ix_offers_status', table_name='listing_offers')
    op.create_index(op.f('ix_listing_offers_buyer_organization_id'), 'listing_offers', ['buyer_organization_id'], unique=False)
    op.create_index(op.f('ix_listing_offers_listing_id'), 'listing_offers', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_offers_status'), 'listing_offers', ['status'], unique=False)
    op.drop_index('ix_listings_batch_id', table_name='marketplace_listings')
    op.drop_index('ix_listings_seller_org_id', table_name='marketplace_listings')
    op.drop_index('ix_listings_status', table_name='marketplace_listings')
    op.create_index(op.f('ix_marketplace_listings_batch_id'), 'marketplace_listings', ['batch_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_seller_branch_id'), 'marketplace_listings', ['seller_branch_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_seller_organization_id'), 'marketplace_listings', ['seller_organization_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_status'), 'marketplace_listings', ['status'], unique=False)
    op.add_column('near_expiry_rules', sa.Column('max_delivery_radius_km', sa.Numeric(precision=6, scale=1), nullable=True))
    op.create_index(op.f('ix_near_expiry_rules_organization_id'), 'near_expiry_rules', ['organization_id'], unique=False)
    op.drop_index('ix_notif_prefs_user_id', table_name='notification_preferences')
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.drop_index('ix_branches_org_id', table_name='pharmacy_branches')
    op.create_index('ix_pharmacy_branches_lat_lng', 'pharmacy_branches', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_pharmacy_branches_organization_id'), 'pharmacy_branches', ['organization_id'], unique=False)
    op.add_column('pharmacy_organizations', sa.Column('trial_used_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('platform_settings_key_key', 'platform_settings', type_='unique')
    op.drop_index('ix_platform_settings_key', table_name='platform_settings')
    op.create_index(op.f('ix_platform_settings_key'), 'platform_settings', ['key'], unique=True)
    op.drop_index('ix_reservations_buyer_org_id', table_name='reservations')
    op.create_index(op.f('ix_reservations_buyer_organization_id'), 'reservations', ['buyer_organization_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.drop_index('ix_transactions_buyer_org_id', table_name='transactions')
    op.drop_index('ix_transactions_seller_org_id', table_name='transactions')
    op.drop_constraint('transactions_listing_id_key', 'transactions', type_='unique')
    op.create_index(op.f('ix_transactions_buyer_organization_id'), 'transactions', ['buyer_organization_id'], unique=False)
    op.create_index(op.f('ix_transactions_listing_id'), 'transactions', ['listing_id'], unique=True)
    op.create_index(op.f('ix_transactions_seller_organization_id'), 'transactions', ['seller_organization_id'], unique=False)
    op.add_column('user_organization_memberships', sa.Column('role_id', sa.UUID(), nullable=True))
    op.drop_index('ix_memberships_org_id', table_name='user_organization_memberships')
    op.drop_index('ix_memberships_user_id', table_name='user_organization_memberships')
    op.create_index(op.f('ix_user_organization_memberships_organization_id'), 'user_organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_organization_memberships_role_id'), 'user_organization_memberships', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_organization_memberships_user_id'), 'user_organization_memberships', ['user_id'], unique=False)
    op.create_foreign_key('fk_memberships_role_id', 'user_organization_memberships', 'org_roles', ['role_id'], ['id'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint('fk_memberships_role_id', 'user_organization_memberships', type_='foreignkey')
    op.drop_index(op.f('ix_user_organization_memberships_user_id'), table_name='user_organization_memberships')
    op.drop_index(op.f('ix_user_organization_memberships_role_id'), table_name='user_organization_memberships')
    op.drop_index(op.f('ix_user_organization_memberships_organization_id'), table_name='user_organization_memberships')
    op.create_index('ix_memberships_user_id', 'user_organization_memberships', ['user_id'], unique=False)
    op.create_index('ix_memberships_org_id', 'user_organization_memberships', ['organization_id'], unique=False)
    op.drop_column('user_organization_memberships', 'role_id')
    op.drop_index(op.f('ix_transactions_seller_organization_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_listing_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_buyer_organization_id'), table_name='transactions')
    op.create_unique_constraint('transactions_listing_id_key', 'transactions', ['listing_id'])
    op.create_index('ix_transactions_seller_org_id', 'transactions', ['seller_organization_id'], unique=False)
    op.create_index('ix_transactions_buyer_org_id', 'transactions', ['buyer_organization_id'], unique=False)
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_buyer_organization_id'), table_name='reservations')
    op.create_index('ix_reservations_buyer_org_id', 'reservations', ['buyer_organization_id'], unique=False)
    op.drop_index(op.f('ix_platform_settings_key'), table_name='platform_settings')
    op.create_index('ix_platform_settings_key', 'platform_settings', ['key'], unique=False)
    op.create_unique_constraint('platform_settings_key_key', 'platform_settings', ['key'])
    op.drop_column('pharmacy_organizations', 'trial_used_at')
    op.drop_index(op.f('ix_pharmacy_branches_organization_id'), table_name='pharmacy_branches')
    op.drop_index('ix_pharmacy_branches_lat_lng', table_name='pharmacy_branches')
    op.create_index('ix_branches_org_id', 'pharmacy_branches', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.create_index('ix_notifications_type', 'notifications', ['notification_type'], unique=False)
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.create_index('ix_notif_prefs_user_id', 'notification_preferences', ['user_id'], unique=False)
    op.drop_index(op.f('ix_near_expiry_rules_organization_id'), table_name='near_expiry_rules')
    op.drop_column('near_expiry_rules', 'max_delivery_radius_km')
    op.drop_index(op.f('ix_marketplace_listings_status'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_seller_organization_id'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_seller_branch_id'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_batch_id'), table_name='marketplace_listings')
    op.create_index('ix_listings_status', 'marketplace_listings', ['status'], unique=False)
    op.create_index('ix_listings_seller_org_id', 'marketplace_listings', ['seller_organization_id'], unique=False)
    op.create_index('ix_listings_batch_id', 'marketplace_listings', ['batch_id'], unique=False)
    op.drop_index(op.f('ix_listing_offers_status'), table_name='listing_offers')
    op.drop_index(op.f('ix_listing_offers_listing_id'), table_name='listing_offers')
    op.drop_index(op.f('ix_listing_offers_buyer_organization_id'), table_name='listing_offers')
    op.create_index('ix_offers_status', 'listing_offers', ['status'], unique=False)
    op.create_index('ix_offers_listing_id', 'listing_offers', ['listing_id'], unique=False)
    op.create_index('ix_offers_buyer_org_id', 'listing_offers', ['buyer_organization_id'], unique=False)
    op.drop_index(op.f('ix_invoices_transaction_id'), table_name='invoices')
    op.create_unique_constraint('invoices_transaction_id_key', 'invoices', ['transaction_id'])
    op.drop_index(op.f('ix_inventory_movements_organization_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_batch_id'), table_name='inventory_movements')
    op.create_index('ix_movements_org_id', 'inventory_movements', ['organization_id'], unique=False)
    op.create_index('ix_movements_batch_id', 'inventory_movements', ['batch_id'], unique=False)
    op.drop_index(op.f('ix_inventory_batches_status'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_product_id'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_organization_id'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_expiry_date'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_branch_id'), table_name='inventory_batches')
    op.create_index('ix_batches_status', 'inventory_batches', ['status'], unique=False)
    op.create_index('ix_batches_product_id', 'inventory_batches', ['product_id'], unique=False)
    op.create_index('ix_batches_org_id', 'inventory_batches', ['organization_id'], unique=False)
    op.create_index('ix_batches_expiry_date', 'inventory_batches', ['expiry_date'], unique=False)
    op.create_index('ix_batches_branch_id', 'inventory_batches', ['branch_id'], unique=False)
    op.create_index('ix_import_jobs_queue', 'import_jobs', ['status', 'created_at'], unique=False)
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.create_index('ix_audit_logs_org_id', 'audit_logs', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_platform_revenue_transaction_id'), table_name='platform_revenue')
    op.drop_index(op.f('ix_platform_revenue_organization_id'), table_name='platform_revenue')
    op.drop_index(op.f('ix_platform_revenue_kind'), table_name='platform_revenue')
    op.drop_index(op.f('ix_platform_revenue_collected_at'), table_name='platform_revenue')
    op.drop_table('platform_revenue')
    op.drop_index('ix_promotion_redemptions_ref', table_name='promotion_redemptions')
    op.drop_index(op.f('ix_promotion_redemptions_promotion_id'), table_name='promotion_redemptions')
    op.drop_index(op.f('ix_promotion_redemptions_organization_id'), table_name='promotion_redemptions')
    op.drop_table('promotion_redemptions')
    op.drop_index(op.f('ix_restock_recommendations_status'), table_name='restock_recommendations')
    op.drop_index(op.f('ix_restock_recommendations_product_id'), table_name='restock_recommendations')
    op.drop_index(op.f('ix_restock_recommendations_organization_id'), table_name='restock_recommendations')
    op.drop_index(op.f('ix_restock_recommendations_kind'), table_name='restock_recommendations')
    op.drop_index(op.f('ix_restock_recommendations_branch_id'), table_name='restock_recommendations')
    op.drop_index(op.f('ix_restock_recommendations_action'), table_name='restock_recommendations')
    op.drop_table('restock_recommendations')
    op.drop_index(op.f('ix_promotions_organization_id'), table_name='promotions')
    op.drop_index('ix_promotions_org_active', table_name='promotions')
    op.drop_index(op.f('ix_promotions_listing_id'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_withdrawal_requests_wallet_id'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_status'), table_name='withdrawal_requests')
    op.drop_table('withdrawal_requests')
    op.drop_index(op.f('ix_wallet_topups_wallet_id'), table_name='wallet_topups')
    op.drop_index(op.f('ix_wallet_topups_status'), table_name='wallet_topups')
    op.drop_index(op.f('ix_wallet_topups_provider_ref'), table_name='wallet_topups')
    op.drop_table('wallet_topups')
    op.drop_index(op.f('ix_wallet_entries_wallet_id'), table_name='wallet_entries')
    op.drop_index(op.f('ix_wallet_entries_reference_type'), table_name='wallet_entries')
    op.drop_index(op.f('ix_wallet_entries_reference_id'), table_name='wallet_entries')
    op.drop_index(op.f('ix_wallet_entries_entry_type'), table_name='wallet_entries')
    op.drop_table('wallet_entries')
    op.drop_index(op.f('ix_team_invites_organization_id'), table_name='team_invites')
    op.drop_index(op.f('ix_team_invites_email'), table_name='team_invites')
    op.drop_table('team_invites')
    op.drop_index(op.f('ix_subscription_invoices_subscription_id'), table_name='subscription_invoices')
    op.drop_index(op.f('ix_subscription_invoices_status'), table_name='subscription_invoices')
    op.drop_index(op.f('ix_subscription_invoices_provider_ref'), table_name='subscription_invoices')
    op.drop_index(op.f('ix_subscription_invoices_organization_id'), table_name='subscription_invoices')
    op.drop_table('subscription_invoices')
    op.drop_index(op.f('ix_subscription_events_subscription_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_organization_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_event_type'), table_name='subscription_events')
    op.drop_table('subscription_events')
    op.drop_index(op.f('ix_wallets_organization_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_usage_ledger_organization_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_metric'), table_name='usage_ledger')
    op.drop_table('usage_ledger')
    op.drop_index(op.f('ix_usage_counters_organization_id'), table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_index(op.f('ix_organization_subscriptions_status'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_organization_id'), table_name='organization_subscriptions')
    op.drop_table('organization_subscriptions')
    op.drop_index(op.f('ix_organization_addons_status'), table_name='organization_addons')
    op.drop_index(op.f('ix_organization_addons_organization_id'), table_name='organization_addons')
    op.drop_index(op.f('ix_organization_addons_code'), table_name='organization_addons')
    op.drop_table('organization_addons')
    op.drop_index(op.f('ix_org_roles_organization_id'), table_name='org_roles')
    op.drop_table('org_roles')
    op.drop_index(op.f('ix_subscription_plans_code'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_table('payment_events')
    # ### end Alembic commands ###
