/**
 * Telling the user what actually went wrong.
 *
 * "فشل تسجيل الدخول" for both a wrong password and a server that never answered
 * sends people looking for the wrong problem — it cost us an hour of doubting a
 * password that was correct the whole time. These cases need different words
 * because they need different actions: check what you typed, wait and retry, or
 * send us the request id.
 *
 * Two rounds of fixes later, the remaining bug was in how this file decided WHO
 * had answered. It read the body shape — `typeof detail === "string"` — and
 * treated that as proof the response came from our API. Shape is not provenance,
 * and it was wrong in both directions:
 *
 *   - The Next proxy answers a backend outage with `{"detail": "..."}` because
 *     that is our shape, so infrastructure read as application and the outage
 *     text was discarded in favour of a generic server error.
 *   - One endpoint answered 422 with `detail` as an object, so a real business
 *     rejection read as infrastructure — "retry" advice for something that can
 *     never succeed by retrying, with the reasons hidden.
 *
 * So provenance is now carried, not guessed: the proxy stamps a header on the
 * responses it generates itself, and the backend was fixed to keep `detail` a
 * string with structure in sibling keys. This file trusts the header, and stays
 * defensive about shapes anyway — a defensive parser is what makes the next
 * violation harmless instead of user-visible.
 *
 * The rule that governs everything below: **the caller's fallback is only ever
 * shown for a genuine authentication answer from our own API.** Nothing else may
 * imply anything about what the person typed.
 */
import { AxiosError, type AxiosResponse } from "axios";

export type FailureKind =
  | "offline"      // the browser has no network at all
  | "unreachable"  // the request never got an answer (server asleep, DNS, CORS)
  | "timeout"      // it answered too slowly
  | "throttled"    // too many requests, from our throttle or from the edge
  | "gateway"      // something answered, but it was not our application
  | "auth"         // the server answered, and said no
  | "server"       // the server answered, and broke
  | "client";      // the server answered, and it was our request

export type Failure = {
  kind: FailureKind;
  /** What to show the person. */
  message: string;
  /** The next thing for them to do, when there is one. */
  hint?: string;
  /** Specific causes behind `message`, when the API sent them (eligibility rules). */
  reasons?: string[];
  status?: number;
  /** Correlation id from the API, so a report can be traced to one request. */
  requestId?: string;
  /** Whether trying again in a moment is likely to work. */
  retryable: boolean;
  /**
   * Whether our application produced this body. False for anything generated by
   * a layer in front of it. Kept on the object so a screen can distinguish an
   * application error from an infrastructure one without re-parsing.
   */
  fromApi: boolean;
};

/** Set by the Next proxy on responses it generates itself. See the route module. */
const PROXY_ERROR_HEADER = "x-api-proxy-error";

/** Said on every failure that is not about the password, so nobody doubts theirs. */
const CREDENTIALS_ARE_FINE = "بياناتك التي أدخلتها سليمة.";

type ApiBody = { detail?: unknown; reasons?: unknown };

/**
 * Read our API's error body.
 *
 * `detail` is a string in every response the backend sends — that is enforced on
 * the backend side. The other shapes here are defence, not contract: FastAPI's
 * own validation detail is a list, and a blob-typed request yields a Blob that
 * cannot be parsed synchronously at all. Each is recognisably ours, so each is
 * reported as an application error rather than being mistaken for infrastructure.
 */
function readApiBody(response: AxiosResponse<ApiBody>): {
  message?: string;
  reasons?: string[];
  fromApi: boolean;
} {
  const data = response.data as unknown;

  // A blob body is ours — we asked for it — but it cannot be read here. Say
  // nothing about it rather than misattributing it to a layer in front.
  if (typeof Blob !== "undefined" && data instanceof Blob) {
    return { fromApi: true };
  }

  // Provenance for everything the proxy header does not cover. Our API answers
  // with a JSON object; the layers in front of it answer with an HTML string.
  // This matters beyond parsing a message: a 401 whose body we cannot read is
  // still an authentication answer, and reporting it as infrastructure would
  // leave the sign-in screen unable to say anything about credentials at all.
  if (data === null || data === undefined || typeof data !== "object") {
    return { fromApi: false };
  }

  const detail = (data as ApiBody).detail;
  const reasons = (data as ApiBody).reasons;

  const asStrings = (value: unknown): string[] | undefined => {
    if (!Array.isArray(value)) return undefined;
    const items = value.filter((v): v is string => typeof v === "string" && v.trim() !== "");
    return items.length > 0 ? items : undefined;
  };

  if (typeof detail === "string" && detail.trim() !== "") {
    return { message: detail.trim(), reasons: asStrings(reasons), fromApi: true };
  }

  // FastAPI's raw validation shape, `[{loc, msg, type}]`. The backend normalises
  // this before it leaves, so reaching here means something bypassed that.
  if (Array.isArray(detail)) {
    const first = detail.find(
      (e) => e && typeof e === "object" && typeof (e as { msg?: unknown }).msg === "string",
    ) as { msg?: string } | undefined;
    if (first?.msg) return { message: first.msg, fromApi: true };
    return { fromApi: true };
  }

  // An object detail. Recognisably ours, so never rendered raw — an object where
  // text was expected is what blanked this page once already.
  if (detail && typeof detail === "object") {
    const message = (detail as { message?: unknown }).message;
    return {
      message: typeof message === "string" && message.trim() !== "" ? message.trim() : undefined,
      reasons: asStrings((detail as { reasons?: unknown }).reasons),
      fromApi: true,
    };
  }

  // An object body with no usable `detail`. Still ours — see above.
  return { reasons: asStrings(reasons), fromApi: true };
}

/** "بعد 3 دقائق" — Arabic needs the dual and the small plural, not a bare number. */
function arabicMinutes(count: number): string {
  if (count <= 1) return "دقيقة";
  if (count === 2) return "دقيقتين";
  if (count <= 10) return `${count} دقائق`;
  return `${count} دقيقة`;
}

function retryAfterHint(response: AxiosResponse): string | undefined {
  const raw = response.headers?.["retry-after"];
  const seconds = Number(raw);
  if (!Number.isFinite(seconds) || seconds <= 0) return undefined;
  // Round up, matching the backend. Rounding down tells someone to come back
  // before the window has actually closed.
  return `أعد المحاولة بعد ${arabicMinutes(Math.ceil(seconds / 60))}.`;
}

/** A generic sentence for a status, used when there is no message we may show. */
function genericFor(status: number): string {
  if (status >= 500) return "حدث خطأ في الخادم";
  return "تعذر إتمام الطلب";
}

export function describeError(error: unknown, fallback: string): Failure {
  const axiosError = error as AxiosError<ApiBody>;
  const response = axiosError?.response;
  const requestId =
    (response?.headers?.["x-request-id"] as string | undefined) ?? undefined;

  // No response at all: the request never completed.
  if (!response) {
    if (typeof navigator !== "undefined" && navigator.onLine === false) {
      return {
        kind: "offline",
        message: "لا يوجد اتصال بالإنترنت",
        hint: "تحقق من اتصالك ثم أعد المحاولة. " + CREDENTIALS_ARE_FINE,
        retryable: true,
        fromApi: false,
      };
    }
    if (axiosError?.code === "ECONNABORTED" || axiosError?.code === "ETIMEDOUT") {
      return {
        kind: "timeout",
        message: "الخادم لم يستجب في الوقت المتوقع",
        hint:
          "الخدمة قد تكون في وضع الخمول وتحتاج لحظات لتستيقظ — أعد المحاولة بعد دقيقة. " +
          CREDENTIALS_ARE_FINE,
        retryable: true,
        fromApi: false,
      };
    }
    return {
      kind: "unreachable",
      message: "تعذر الوصول إلى الخادم",
      hint:
        "لم يصل رد من الخادم. قد يكون قيد التحديث أو في وضع الخمول — أعد المحاولة بعد لحظات. " +
        CREDENTIALS_ARE_FINE,
      retryable: true,
      fromApi: false,
    };
  }

  const status = response.status;
  const body = readApiBody(response);
  const { fromApi } = body;

  // Checked first: our own proxy said the application never saw this request.
  // Its text is the most accurate description of the outage we have, so it is
  // shown rather than replaced by a generic server error.
  const proxyError = response.headers?.[PROXY_ERROR_HEADER] as string | undefined;
  if (proxyError) {
    const misconfigured = proxyError === "not-configured";
    return {
      kind: "gateway",
      message: body.message ?? "تعذر الوصول إلى الخادم",
      hint:
        (misconfigured
          ? "إعداد الخدمة غير مكتمل — أبلغ الدعم الفني. "
          : "الخدمة قد تكون قيد التحديث أو تستيقظ من الخمول — أعد المحاولة بعد لحظات. ") +
        CREDENTIALS_ARE_FINE,
      status,
      requestId,
      // Retrying a missing configuration changes nothing.
      retryable: !misconfigured,
      fromApi: false,
    };
  }

  // A rate limit, whether ours or an edge's, and never a statement about credentials.
  if (status === 429) {
    return {
      kind: "throttled",
      message: body.message ?? "محاولات كثيرة خلال وقت قصير",
      // One authoritative duration per response. When the message is ours it
      // already names the wait, and appending a second computed one showed two
      // different numbers for the same wait — floor on the server, ceil here.
      hint: fromApi
        ? CREDENTIALS_ARE_FINE
        : `${retryAfterHint(response) ?? "انتظر قليلا ثم أعد المحاولة."} ${CREDENTIALS_ARE_FINE}`,
      status,
      requestId,
      retryable: true,
      fromApi,
    };
  }

  // The body is not ours and no proxy marker: a layer in front answered, so the
  // application never saw this. Report that, never the caller's fallback.
  if (!fromApi) {
    const waking = status === 502 || status === 503 || status === 504;
    return {
      kind: "gateway",
      message: waking ? "الخدمة غير متاحة حاليا" : "رد غير متوقع من الخادم",
      hint:
        (waking
          ? "قد تكون قيد التحديث أو تستيقظ من الخمول — أعد المحاولة بعد لحظات. "
          : `الرد لم يأت من التطبيق نفسه (HTTP ${status}). أعد المحاولة، وإن تكرر أرسل لنا هذا الرمز. `) +
        CREDENTIALS_ARE_FINE,
      status,
      requestId,
      retryable: true,
      fromApi,
    };
  }

  // From here on the answer is ours, so `fallback` becomes permissible — but
  // only on the branch that is genuinely about credentials.
  if (status === 401 || status === 403) {
    return {
      kind: "auth",
      message: body.message ?? fallback,
      status,
      requestId,
      retryable: false,
      fromApi,
    };
  }
  if (status >= 500) {
    return {
      kind: "server",
      message: body.message ?? genericFor(status),
      hint: requestId
        ? `أعد المحاولة، وإن تكرر أرسل لنا رقم الطلب: ${requestId}`
        : "أعد المحاولة، وإن تكرر تواصل مع الدعم.",
      status,
      requestId,
      retryable: true,
      fromApi,
    };
  }
  return {
    kind: "client",
    message: body.message ?? genericFor(status),
    reasons: body.reasons,
    status,
    requestId,
    retryable: false,
    fromApi,
  };
}

/**
 * The technical line under a failure, or `null` when there is nothing to show.
 *
 * It exists so a screenshot names the responsible layer without anyone reading
 * the server logs. But it is rendered on a customer-facing Arabic sign-in page,
 * and an unguarded version printed the bare English token `offline` to end users
 * — for a failure that has no status and no request id, there is no evidence in
 * it, only noise. So: shown only when it carries something a report could use.
 */
export function diagnosticsLine(failure: Failure): string | null {
  if (!failure.status && !failure.requestId) return null;
  return [
    failure.kind,
    failure.status ? `HTTP ${failure.status}` : null,
    failure.status && !failure.fromApi ? "not-from-api" : null,
    failure.requestId,
  ]
    .filter(Boolean)
    .join(" · ");
}

/** A single line suitable for a toast. */
export function errorMessage(error: unknown, fallback: string): string {
  const failure = describeError(error, fallback);
  const reasons = failure.reasons?.length ? ` — ${failure.reasons.join("؛ ")}` : "";
  const hint = failure.hint ? ` — ${failure.hint}` : "";
  return `${failure.message}${reasons}${hint}`;
}
